version: '3.9'
services:
  static:
    build:
      context: .
    expose:
      - 5000:5000
    image: cars-test
    environment:
      MODE: production
      PORT: 5000
      MONGOOSE: mongodb://mongo/cars-test
    networks: 
      - mongo-network
      
networks: 
  mongo-network:
    name: mongo-network
    driver: bridge
    external: true