version: '3.9'
services:
  static:
    build:
      context: .
    ports:
      - "5000:5000"
    image: hukakhepak/cars-test
    environment:
      MODE: production
      PORT: 5000
      MONGO: mongodb://root:example@mongo:27017/
      MONGOOSE: mongodb://root:example@mongo:27017/