version: '3.9'
services:
  static:
    build:
      context: .
    container_name: cars
    image: cars-test
    environment:
      MODE: production
      PORT: 5000
      MONGO: mongodb://mongo/cars
    networks: 
      - mongo-network
      
networks: 
  mongo-network:
    name: mongo-network
    driver: bridge
    external: true