version: '3.9'
services:
  app:
    build:
      context: .
    image: cars-test
    container_name: interpreter
    environment:
      MODE: production
      PORT: 5000
      MONGO: mongodb://mongo/interpreter
    networks: 
      - nginx-network
      
networks: 
  nginx-network:
    name: nginx-network
    driver: bridge
    external: true